-- Fix Currency Precision (Float to Decimal)

-- 1. Bookings Table
ALTER TABLE bookings MODIFY COLUMN agreement_value DECIMAL(15,2) NOT NULL DEFAULT 0.00;
ALTER TABLE bookings MODIFY COLUMN total_received DECIMAL(15,2) NOT NULL DEFAULT 0.00;
ALTER TABLE bookings MODIFY COLUMN total_pending DECIMAL(15,2) NOT NULL DEFAULT 0.00;
ALTER TABLE bookings MODIFY COLUMN rate DECIMAL(10,2) DEFAULT NULL;

-- 2. Booking Demands Table
ALTER TABLE booking_demands MODIFY COLUMN demand_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00;
ALTER TABLE booking_demands MODIFY COLUMN paid_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00;

-- 3. Payments Table
ALTER TABLE payments MODIFY COLUMN amount DECIMAL(15,2) NOT NULL DEFAULT 0.00;

-- 4. Flats (Total Value)
ALTER TABLE flats MODIFY COLUMN total_value DECIMAL(15,2) NOT NULL DEFAULT 0.00;

-- 5. Challans and Bills
ALTER TABLE challans MODIFY COLUMN total_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00;
ALTER TABLE challans MODIFY COLUMN paid_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00;
ALTER TABLE challans MODIFY COLUMN pending_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00;

ALTER TABLE bills MODIFY COLUMN amount DECIMAL(15,2) NOT NULL DEFAULT 0.00;
ALTER TABLE bills MODIFY COLUMN paid_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00;
